version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_innovatech
    restart: always
    environment:
      MYSQL_DATABASE: innovatech_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  backend-ventas:
    image: colmay2005/innovatech-back-ventas:latest
    container_name: back_ventas
    restart: always
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovatech_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
    depends_on:
      - db
    networks:
      - backend-network

  backend-despachos:
    image: colmay2005/innovatech-back-despachos:latest
    container_name: back_despachos
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovatech_db
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: dbpassword
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  db_data:

networks:
  backend-network:
    driver: bridge