name: CI/CD Pipeline

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #################################################
      # BACKEND DESPACHOS
      #################################################
      - name: Build y Push Backend Despachos
        uses: docker/build-push-action@v4
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          file: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/back-despachos:latest

      #################################################
      # BACKEND VENTAS
      #################################################
      - name: Build y Push Backend Ventas
        uses: docker/build-push-action@v4
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          file: ./back-Ventas_SpringBoot/Springboot-API-REST/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/back-ventas:latest

      #################################################
      # FRONTEND
      #################################################
      - name: Build y Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./front_despacho
          file: ./front_despacho/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/front-despachos:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy en EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ir al directorio personal
            cd /home/${{ secrets.EC2_USER }}

            # Variables de entorno
            export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

            # Usamos la ruta absoluta del binario para que no falle el "command not found"
            # Generalmente está en /usr/bin/docker-compose o /usr/local/bin/docker-compose
            # El comando 'sudo' es necesario para asegurar la ejecución
            sudo docker-compose pull
            sudo docker-compose down
            sudo docker-compose up -d